image: Visual Studio 2019

init:
  - git config --global core.autocrlf input

environment:
  MSBUILD_LOGGER: C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll

build_script:
  - msbuild build\AppVeyor.proj /r /t:UpdateBuildVersion /logger:"%MSBUILD_LOGGER%"
  - msbuild Moq.sln /r /t:Build;Test;Pack /logger:"%MSBUILD_LOGGER%"

test: off

deploy:
  - provider: NuGet
    api_key:
      secure: wyNu3w7gmiC5q4iQiQ7G6stNtSryNe2v0W8CRHe6n5UOPTx1S3rVdxXq62LTr58Y
    on:
      appveyor_repo_tag: true

nuget:
  project_feed: true

artifacts:
  - path: 'out\*.nupkg'
